export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  TENANT_ADMIN = "TENANT_ADMIN",
  EDITOR = "EDITOR",
  VIEWER = "VIEWER",
}
export enum SubscriptionPlan {
  FREE = "FREE",
  STARTUP = "STARTUP",
  PRO = "PRO",
  ENTERPRISE = "ENTERPRISE",
}
export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  CANCELED = "CANCELED",
  EXPIRED = "EXPIRED",
}
export enum PaymentProvider {
  STRIPE = "STRIPE",
  LEMONSQUEEZY = "LEMONSQUEEZY",
  LENCO = "LENCO",
}
export enum PaymentStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}
export enum AuditAction {
  SUPER_TENANT_CREATE = "SUPER_TENANT_CREATE",
  SUPER_TENANT_UPDATE = "SUPER_TENANT_UPDATE",
    SUPER_TENANT_DELETE = "SUPER_TENANT_DELETE",
    TENANT_SUBSCRIPTION_UPDATE = "TENANT_SUBSCRIPTION_UPDATE",
    TENANT_SUBSCRIPTION_CANCEL = "TENANT_SUBSCRIPTION_CANCEL",
    USER_INVITE = "USER_INVITE",
    USER_UPDATE = "USER_UPDATE",
    USER_DELETE = "USER_DELETE",
    CAMPAIGN_CREATE = "CAMPAIGN_CREATE",
    CAMPAIGN_UPDATE = "CAMPAIGN_UPDATE",
    CAMPAIGN_DELETE = "CAMPAIGN_DELETE",
    FLYER_CREATE = "FLYER_CREATE",
    FLYER_UPDATE = "FLYER_UPDATE",
    FLYER_DELETE = "FLYER_DELETE",
    SHORTLINK_CREATE = "SHORTLINK_CREATE",
    SHORTLINK_UPDATE = "SHORTLINK_UPDATE",
    SHORTLINK_DELETE = "SHORTLINK_DELETE",
}
export enum FeedbackType {
  BUG = "BUG",
  FEATURE_REQUEST = "FEATURE_REQUEST",
  OTHER = "OTHER",
}
export enum FeedbackStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}
